package test;

import java.util.*;

/**
 * Třída obsahující množinu testovacích scénářů.
 * <p>
 * Toto rozhraní je součástí jednoduché textové adventury s grafickým rozhraním.
 *
 * @author Jan Říha
 * @author Alena Kalivodová
 * @version LS-2021, 2021-05-26
 */

public class Scenarios {

    /**
     * Soukromý konstruktor. Zajistí, že nebude možné vytvářet instance této třídy.
     */
    private Scenarios() {
    }

    public static final Set<Scenario> SCENARIOS = new HashSet();
    public static final Scenario GENDER = new Scenario("GENDER");
    public static final Scenario NAME = new Scenario("GENDER");
    public static final Scenario WEAPON = new Scenario("NAME");
    public static final Scenario WEAPONDROP = new Scenario("WEAPONDROP");
    public static final Scenario PLAYER = new Scenario("PLAYER");
    public static final Scenario PARTNER = new Scenario("PARTNER");
    public static final Scenario LOOK = new Scenario("LOOK");
    public static final Scenario EXPLORE = new Scenario("EXPLORE");
    public static final Scenario PICKUP = new Scenario("PICKUP");
    public static final Scenario DROP = new Scenario("DROP");
    public static final Scenario INVENTORY = new Scenario("INVENTORY");
    public static final Scenario ATTACK = new Scenario("ATTACK");
    public static final Scenario ATTACK_PARTNER = new Scenario("ATTACK_PARTNER");
    public static final Scenario GIVE = new Scenario("GIVE");
    public static final Scenario TALK = new Scenario("TALK");
    public static final Scenario GO = new Scenario("GO");
    public static final Scenario JUST_AS_PLANED = new Scenario("JUST_AS_PLANED");
    public static final Scenario GENERALS_ROCK = new Scenario("GENERALS_ROCK");
    public static final Scenario GENERAL_CHIT_CHAT = new Scenario("GENERAL_CHIT_CHAT");
    public static final Scenario GUARD_CHIT_CHAT = new Scenario("GUARD_CHIT_CHAT");
    public static final Scenario TUES_STICK = new Scenario("TUES_STICK");
    static {
        SCENARIOS.add(GENDER);
        SCENARIOS.add(NAME);
        SCENARIOS.add(WEAPON);
        SCENARIOS.add(WEAPONDROP);
        SCENARIOS.add(PLAYER);
        SCENARIOS.add(PARTNER);
        SCENARIOS.add(LOOK);
        SCENARIOS.add(EXPLORE);
        SCENARIOS.add(PICKUP);
        SCENARIOS.add(DROP);
        SCENARIOS.add(INVENTORY);
        SCENARIOS.add(ATTACK);
        SCENARIOS.add(ATTACK_PARTNER);
        SCENARIOS.add(GIVE);
        SCENARIOS.add(TALK);
        SCENARIOS.add(GO);
        SCENARIOS.add(JUST_AS_PLANED);
        SCENARIOS.add(GENERALS_ROCK);
        SCENARIOS.add(GENERAL_CHIT_CHAT);
        SCENARIOS.add(GUARD_CHIT_CHAT);
        SCENARIOS.add(TUES_STICK);

        GENDER
                .addStep(new Step()
                        .setAction("pohlaví")
                        .setMessage("\nKteré pohlaví si chceš vybrat. Máš na výběr mezi mužem a ženou."))
                .addStep(new Step()
                        .setAction("pohlaví j k")
                        .setMessage("Můžeš mít pouze jednou pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví j")
                        .setMessage("\nJe mi líto, že tě zklamu, ale takhle hra zná jen dvě pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž")
                        .setMessage("\nPohlaví nastaveno na: muž.\n\n\n" +
                                "Pomalu otevíráš oči a vidíš před sebou rozmazanou siluetu obrovského muže.\n" +
                                "Mezitím, co se snažíš opartně posadit, se k tobě muž otočí a přispěchá ti na pomoc.\n" +
                                "???: Dobré ráno. Jak se cítíš? Slyšel jsem od Yrsy, co stalo. Ti vojáci opravdu nezají hranic...\n " +
                                "Že se nestydí chtít popravit malou holčičku. Vypadá to, že Tua uvěznili za to, že si jí zastal.\n " +
                                "Musíte se ho vydat brzy zachránit. Ale v tomhle stavu si nejsem jistný, jestli to zvládnete...\n " +
                                "Vnímáš mě? Pamatuješ vůbec svoje jméno?\n " +
                                "///Zkus si vzpomenout, jak se jmenuješ. Napiš jméno tvé_jméno///\n"))
                .addStep(new Step()
                        .setAction("pohlaví žena")
                        .setMessage("\nUž sis pohlavní vybral/a."));
        NAME
                .addStep(new Step()
                        .setAction("jméno")
                        .setMessage("\nVyber si nejdří své pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno")
                        .setMessage("\nA jak se chceš jmenovat."))
                .addStep(new Step()
                        .setAction("jméno j k")
                        .setMessage("\nPokud chceš mít víceslovné jméno, tak použij třeba podtržítko."))
                .addStep(new Step()
                        .setAction("jméno j")
                        .setMessage("\nJméno nastaveno na: j\n\n" +
                                "j: Ehhh? Já jsem j, že jo? Jsi to ty Gorme?\n" +
                                "Gorm: Jo, to jsem já.\n" +
                                "j: Kde je Yrsa a Tue?\n" +
                                "Gorm: No, Yrsa je táhle, ale jak jsem už říkal, Tua zavřeli. Yrsa: Kdyby jenom to... Zatáhli ho do té nechvalně prosnulé mučírny a potom, co si tam s ním budou týden hrát, ho nechají pověsit\n" +
                                "Gorm: Zpomal trochu. Oba jste na tom zatím celkem špatně. Pomalu se vzpamatuje, vemte si zbraně a pak mu běžte na pomoc.\n" +
                                " Já vám sice v boji k ničemu nebudu, ale v místosti za kovárnou si můžete vzít meč, sekeru nebo nůž, na zbytku zatím pracuju.\n" +
                                "Yrsa: Za chvilku se k tobě přidám, jen si ještě chvilku odpočinu.\nAktuální lokace: kemp\n" +
                                "Popis lokace: Kemp, který jste založili se svými přítale,je chráněn silnou magickou bariérou, takže žádný příšery se sem nedostanou.\n"))
                .addStep(new Step()
                        .setAction("jméno k")
                        .setMessage("\nUž sis jméno vybral/a."));
        WEAPON
                .addStep(new Step()
                        .setAction("zbraň")
                        .setMessage("\nNejdřív si vyber pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("zbraň")
                        .setMessage("\nNejdřív si vyber jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít_do kovárna"))
                .addStep(new Step()
                        .setAction("jít_do místnost"))
                .addStep(new Step()
                        .setAction("zbraň")
                        .setMessage("\nA kterou zbraň chceš?."))
                .addStep(new Step()
                        .setAction("zbraň j k")
                        .setMessage("\nMůžeš mít jenom jednu zbraň."))
                .addStep(new Step()
                        .setAction("zbraň j")
                        .setMessage("\nTaková zbraň tu není."))
                .addStep(new Step()
                        .setAction("zbraň greatsword")
                        .setMessage("\nTuhle zbraň si vzít nemůžeš"))
                .addStep(new Step()
                        .setAction("zbraň nůž")
                        .setMessage("\nGorm: Dobře, tady máš.\n" +
                                "Zbraň nastavena na: nůž"))
                .addStep(new Step()
                        .setAction("zbraň sekera")
                        .setMessage("\nMusíš nejdřív položit zbraň, kterou máš u sebe, než si vezmeš jinou."));
        WEAPONDROP
                .addStep(new Step()
                        .setAction("odložit_zbraň")
                        .setMessage("\nNejdřív si vyber pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("odložit_zbraň")
                        .setMessage("\nNejdřív si vyber jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("odložit_zbraň")
                        .setMessage("\nNejdřív si zbraň aspoň vezmi, než ji budeš odkládat."))
                .addStep(new Step()
                        .setAction("jít_do kovárna"))
                .addStep(new Step()
                        .setAction("jít_do místnost"))
                .addStep(new Step()
                        .setAction("zbraň nůž"))
                .addStep(new Step()
                        .setAction("odložitz j")
                        .setMessage("\nStačí napsat odložitz."))
                .addStep(new Step()
                        .setAction("jít_do kovárna"))
                .addStep(new Step()
                        .setAction("odložitz")
                        .setMessage("\nZbraň musíš odložit v místnosti za kovárnou."))
                .addStep(new Step()
                        .setAction("jít_do místnost"))
                .addStep(new Step()
                        .setAction("odložitz")
                        .setMessage("\nOdložil/a si svou zbraň."));
        PLAYER
                .addStep(new Step()
                        .setAction("hráč")
                        .setMessage("\nPředtím, než se budeš moct prohlížet své staty, si nastav pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("hráč")
                        .setMessage("\nPředtím, než se budeš moct prohlížet své staty, si nastav jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("hráč")
                        .setMessage("\nPředtím, než se budeš moct prohlížet své staty, si vyber zbraň."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň nůž")
                        .setPlayer("\nPohlaví: muž\n" +
                                "Jméno: j\n" +
                                "Zbraň: nůž\n" +
                                "Životy: 30.0\n" +
                                "Síla: 13.0"));
        PARTNER
                .addStep(new Step()
                        .setAction("parťák")
                        .setMessage("\nPředtím, než se budeš moct prohlížet staty svého parťáka, si nastav pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("parťák")
                        .setMessage("\nPředtím, než se budeš moct prohlížet staty svého parťáka, si nastav jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("parťák")
                        .setMessage("\nPředtím, než se budeš moct prohlížet staty svého parťáka, si vyber zbraň."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň nůž")
                        .setPartner("\nJméno: Yrsa\n" +
                                "Zbraň: nůž\n" +
                                "Životy: 20.0\n" +
                                "Síla: 10.4"));
        LOOK
                .addStep(new Step()
                        .setAction("rozhlédnout_se")
                        .setMessage("\nNastav si pohlaví a pak až pak se rozhlížej."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("rozhlédnout")
                        .setMessage("\nNastav si jméno a pak až pak se rozhlížej."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("rozhlédnout_se j")
                        .setMessage("\nStačí napsat rozhlédnout_se"))
                .addStep(new Step()
                        .setAction("rozhlédnout_se")
                        .setItems("keř", "kbelík", "panák", "kámen")
                        .setExits("kovárna", "les", "alej", "hora", "stan", "jezero"));
        EXPLORE
                .addStep(new Step()
                        .setAction("prozkoumat")
                        .setMessage("\nNemůžeš prozkoumávat věci, dokud si nenastavíš pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("prohledat")
                        .setMessage("\nnNemůžeš prozkoumávat věci, dokud si nenastavíš jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("prohledat")
                        .setMessage("\nMusíš mi říct, co by si chtěl/a prozkoumat."))
                .addStep(new Step()
                        .setAction("prohledat j k")
                        .setMessage("\nNemůžeš prozkoumávat víc věcí najednou."))
                .addStep(new Step()
                        .setAction("prohledat j")
                        .setMessage("\nNic takového tu není."))
                .addStep(new Step()
                        .setAction("prohledat keř")
                        .setMessage("\nKeř vedle stanu. Gorm si z něj rád trhá borůvky."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň nůž"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prohledat velký_kámen")
                        .setMessage("\nNašel/a jsi: svítící_kámen\nJediná věc, která zde vyčnívá."))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom")
                        .setMessage("\nNašel/a jsi: truhla\nVelký divně rostlý strom. " +
                                "Pod jejími kořeny je vidět truhla. A ještě více pod ní je vidět i něco jiného. " +
                                "Zkus to ještě trochu prozkoumat."))
                .addStep(new Step()
                        .setAction("prohledat velký_strom")
                        .setMessage("\nNašel/a jsi: taška"))
                .addStep(new Step()
                        .setAction("prohledat truhla")
                        .setMessage("\nTruhla je zamčená, ani brutální síla nepomáhá v jejím otevření."));
        PICKUP
                .addStep(new Step()
                        .setAction("vzít")
                        .setMessage("\nNejdřív si nastav pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("vzít")
                        .setMessage("\nNastav si jméno a až pak si sbírej."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("vzít")
                        .setMessage("\nA co chceš sebrat?"))
                .addStep(new Step()
                        .setAction("vzít j k")
                        .setMessage("\nNemůžeš sbírat víc věcí najednou, vyber si jednu."))
                .addStep(new Step()
                        .setAction("vzít j")
                        .setMessage("\nNic takového tu není."))
                .addStep(new Step()
                        .setAction("vzít keř")
                        .setMessage("\nTohle si vzít nemůžeš."))
                .addStep(new Step()
                        .setAction("vzít kámen")
                        .setMessage("\nSebral/a jsi kámen"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat postele"))
                .addStep(new Step()
                        .setAction("vzít polštář"))
                .addStep(new Step()
                        .setAction("prohledat zbytky"))
                .addStep(new Step()
                        .setAction("vzít chleba"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň nůž"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prohledat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen")
                        .setMessage("\nNemáš už v batohu volné místo."));
        DROP
                .addStep(new Step()
                        .setAction("zahodit")
                        .setMessage("\nNemůžeš zahazovat věci, dokud sis nevybral/a pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("položit")
                        .setMessage("\nNemůžeš zahazovat věci, dokud sis nevybral/a jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("zahodit")
                        .setMessage("\nMusíš mi říct, co chceš zahodit."))
                .addStep(new Step()
                        .setAction("položit j k")
                        .setMessage("\nNemůžeš zahodit víc věci najednou."))
                .addStep(new Step()
                        .setAction("zahodit j")
                        .setMessage("\nNemůžeš zahodit něco, co nemáš."))
                .addStep(new Step()
                        .setAction("vzít kámen")
                        .setItems("keř", "kbelík", "panák"))
                .addStep(new Step()
                        .setAction("zahodit kámen")
                        .setMessage("\nZahodil/a jsi kámen")
                        .setItems("kámen", "keř", "kbelík", "panák"));
        INVENTORY
                .addStep(new Step()
                        .setAction("batoh")
                        .setMessage("\nSvůj inventář si můžeš prohlédnout potom, co si nastavíš pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("inventář")
                        .setMessage("\nSvůj inventář si můžeš prohlédnout, potom co si nastavíš jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("batoh j")
                        .setMessage("\nStačí napsat inventář."))
                .addStep(new Step()
                        .setAction("vzít kámen")
                        .setInvenotry("kámen"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka")
                        .setInvenotry("kámen", "propustka"))
                .addStep(new Step()
                        .setAction("zahodit kámen")
                        .setMessage("kámen")
                        .setInvenotry("propustka"));
        ATTACK
                .addStep(new Step()
                        .setAction("útok")
                        .setMessage("\nPřed útočením si vyber pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("zaútoč_na")
                        .setMessage("\nPřed útočením si vyber jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("útok")
                        .setMessage("\nJe těžké útočit, když nemáš zbraň."))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("zaútoč_na")
                        .setMessage("\nNa koho chceš zaútočit? To musíš napsat také."))
                .addStep(new Step()
                        .setAction("útok j k")
                        .setMessage("\nNemůžeš útočit na víc nepřátel najednou."))
                .addStep(new Step()
                        .setAction("útok j")
                        .setMessage("\nNemůžeš útočit na někoho, kdo tu není."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("útok gorm")
                        .setMessage("\nProč útočit na Gorma????"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll")
                        .setMessage("\nDal/a si 15.0 poškození. Tvůj oponent teď má 15.0 životů.\n" +
                                "přerostlý_troll ti útok oplatil a způsobil ti 10.0 poškození. " +
                                "Teď máš 20.0 životů.")
                        .setNpcs("přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll")
                        .setMessage("\nZabil/a si: přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("útok generál")
                        .setMessage("You died.")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
        ATTACK_PARTNER
                .addStep(new Step()
                        .setAction("útokp")
                        .setMessage("\nNech svého parťáka zatím odpočívat a vyber si pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("zaútoč_s_parťákem")
                        .setMessage("\nNech svého parťáka zatím odpočívat a vyber si jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("útokp")
                        .setMessage("\nNech svého parťáka zatím odpočívat a jdi si pro zbraň."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("útokp")
                        .setMessage("\nA a koho chceš zaútočit?"))
                .addStep(new Step()
                        .setAction("útokp j k")
                        .setMessage("\nAni Yrsa neumí útočit na více nepřátel najednou."))
                .addStep(new Step()
                        .setAction("útokp j")
                        .setMessage("\nNemůžeš útočit na někoho, kdo tu není."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("útokp gorm")
                        .setMessage("\nNení důvod útočit na toto npc."))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll")
                        .setMessage("\nYrsa dal/a 10.4 poškození. Tvůj oponent teď má 19.6 životů.\n" +
                                "přerostlý_troll útok oplatil a způsobil 10.0 poškození. Yrsa teď má 10.0 životů."))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll")
                        .setMessage("Tvůj partner umřel.")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
        GIVE
                .addStep(new Step()
                        .setAction("dát")
                        .setMessage("\nNemůžeš dávat věci, dokud si nenastavíš pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("nabídnout")
                        .setMessage("\nNemůžeš dávat věci, dokud si nenastavíš jméno."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("dát")
                        .setMessage("\nMusíš napsat taky komu chceš něco dát a co to něco má být."))
                .addStep(new Step()
                        .setAction("dát b")
                        .setMessage("\nMusíš napsat taky komu chceš něco dát a co to něco má být."))
                .addStep(new Step()
                        .setAction("dát b b b")
                        .setMessage("\nNemůžeš dávat víc věcí najednou. Vyber si jednu."))
                .addStep(new Step()
                        .setAction("dát b j")
                        .setMessage("\nNemůžeš někomu dát něco, co nemáš."))
                .addStep(new Step()
                        .setAction("vzít kámen"))
                .addStep(new Step()
                        .setAction("dát gorm kámen")
                        .setMessage("\nNemůžeš dávat věci někomu, kdo tu není."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm kámen")
                        .setMessage("\nTohle téhle postavě dát nemůžeš."))
                .addStep(new Step()
                        .setAction("zahodit kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prozkoumat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("prozkoumat postele"))
                .addStep(new Step()
                        .setAction("vzít polštář"))
                .addStep(new Step()
                        .setAction("zahodit kámen"))
                .addStep(new Step()
                        .setAction("prozkoumat zbytky"))
                .addStep(new Step()
                        .setAction("vzít chleba"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen")
                        .setMessage("\nDal/a jsi Gormovi svítící_kámen.\n" +
                                "Gorm:To je přesně to, co jsem potřeboval k dokončení zbraní, už si můžeš vzít nějakou z těch lepších."))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka")
                        .setMessage("\nStráž: Vaše propustka vypadá v pořádku. Můžete do města."))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát generál taška")
                        .setMessage("\nGenerál: Tomu říkám domluva. A teď vypadněte ať už se na vás nemusím koukat."))
                .addStep(new Step()
                        .setAction("dát žebrák chleba")
                        .setMessage("\nNo, pořád lepší než nic... Výměnou za něj vám můžu říct, že poblíž hory, které je za městem,\n" +
                                " si prý kdysi někdo schoval poklad."))
                .addStep(new Step()
                        .setAction("jít ghetto"))
                .addStep(new Step()
                        .setAction("prozkoumat odpadky"))
                .addStep(new Step()
                        .setAction("vzít peníz"))
                .addStep(new Step()
                        .setAction("dát malá_holčička polštář")
                        .setMessage("\nAwwwwwwwwwwwwwwwwww. To je ale úplně úžasně chlupatý polštářek!!! Opravdu mi ho jen tak dáte?"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát žebrák peníz")
                        .setMessage("\nDíky díky. Jinak nejsem hlupák, moc dobře vím, kdo jste a koho tu hledáte. Takže infromace přímo pro vás.\n" +
                                "Vchod do podzemního vězení hlídá jen starý nevrlý dědek, který miluje chlast nadevšechno na světě.\n" +
                                "Vždycky si schovává aspoň jeden džbán s pivem poblíž, teď když o něm víte, tak to určitě najdete."))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("vzít pivo"))
                .addStep(new Step()
                        .setAction("vzít pochodeň")
                        .setMessage("\nStráž: Nesahej na to a vypadni!"))
                .addStep(new Step()
                        .setAction("dát stráž pivo")
                        .setMessage("\nStráž: Pivčo no jooooo. Pohlídali byste to tu chvilku místo mě?\n" +
                                " Jen si skočim a hned jsem zpátky."))
                .addStep(new Step()
                        .setAction("vzít pochodeň")
                        .setMessage("\nSebral/a jsi pochodeň"));
        TALK
                .addStep(new Step()
                        .setAction("mluvit_s")
                        .setMessage("\nS ostatními můžeš mluvit po výběru pohlaví."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("mluvit")
                        .setMessage("\nS ostatními můžeš mluvit po výběru jména."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("mluvit")
                        .setMessage("\nA s kým chceš mluvit."))
                .addStep(new Step()
                        .setAction("mluvit j k")
                        .setMessage("\nMůžeš mluvit jen s jedním člověkem najednou."))
                .addStep(new Step()
                        .setAction("mluvit kámen")
                        .setMessage("\nJeště nejsi na tolik šílený/á, aby si mluvl/a s předmětem..."))
                .addStep(new Step()
                        .setAction("mluvit gorm")
                        .setMessage("\nNemůžeš mluvit s někým, kdo tu není."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("mluvit gorm")
                        .setMessage("\nGorm: Chudák Tue, neměli jste se do té popravy plést...\n" +
                                "Ale chápu, že jste se prostě nemohli dívat, jak veřejně popravují malou holčičku..."))
                .addStep(new Step()
                        .setAction("mluvit gorm")
                        .setMessage("\nGorm: Bude obtížné dostat se do města, ale zřejmě ho drží ve skrytém podzemím\n" +
                                "žaláři, buďte obzvlášť opatrní, nevím, co bych dělal, kdybych vás ztratil všechny ..."))
                .addStep(new Step()
                        .setAction("mluvit gorm")
                        .setMessage("\nGorm: Ah, právě jsem si vzpomněl, že někde mezi papíry ve stanu by mělo být povolení ke vstupu do města,\n" +
                                " pokud jste si ho ještě nevzali, tak to udělejte. Jinak se tam pravděpodobně vůbec nedostanete."))
                .addStep(new Step()
                        .setAction("mluvit gorm")
                        .setMessage("\nUž jste si povídali až až."))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("mluvit žába")
                        .setMessage("\nNení důvod."));
        GO
                .addStep(new Step()
                        .setAction("jít")
                        .setMessage("\nVyber si pohlaví, než někam půjdeš."))
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jít")
                        .setMessage("\nVyber si jméno, než někam půjdeš."))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít")
                        .setMessage("\nA kam to bude?"))
                .addStep(new Step()
                        .setAction("jít j k")
                        .setMessage("\nNemůžeš jít na víc míst najednou."))
                .addStep(new Step()
                        .setAction("jít j")
                        .setMessage("\nOdtud se tam nedostaneš."))
                .addStep(new Step()
                        .setAction("jít jezero")
                        .setMessage("\nOpravdu si myslíš, že tě Gorm nechá opustit oblast kempu bez zbraně? Nějakou si vem."))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít les")
                        .setMessage("\nAktuální lokace: les\nPopis lokace: Temný nebezpečný les, nic dobrého tu nenajdeš." +
                                "\nZaútočil na tebe troll.\n" +
                                "Ztratil/a jsi 5.0 zdraví."))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora")
                        .setMessage("\nAktuální lokace: hora\n" +
                                "Popis lokace: Je tu poměrně velká hora. Není důvod jít nahoru, ale tady dole ještě může být něco užitečného.\n" +
                                "Ale teď bys měl/a něco udělat s králíky, kteří na tebe z ničeho nic zaútočili.\n" +
                                "Schovávají se, ale pokud se vrátíš, pravděpodobně zaútočí znovu.\n" +
                                "\nZaútočili na tebe divocí králíci.\nZtratil/a jsi 3.0 zdraví."))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("jít brána")
                        .setMessage("Musíš se nejdřív zbavit přerostlého trolla."))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("jít město")
                        .setMessage("Strážný vás nepustí dovnitř, pokud mu nepředložíte doklady o povolení ke vstupu do města."))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít ghetto")
                        .setMessage("Králův vrchní generál tě nenechá odejít. Musíte s ním jednat."))
                .addStep(new Step()
                        .setAction("dát generál taška"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("jít žalář")
                        .setMessage("Zbavte se strážce a vezměte si pochodeň, než půjdete dovnitř.."))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít průchod"))
                .addStep(new Step()
                        .setAction("jít nádvoří")
                        .setMessage("\nTy mi opravdu nevěříš co?"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("útok stráž"))
                .addStep(new Step()
                        .setAction("jít žalář")
                        .setMessage("\nBez pochodně tam nejdeš."))
                .addStep(new Step()
                        .setAction("vzít pochodeň"))
                .addStep(new Step()
                        .setAction("jít žalář"))
                .addStep(new Step()
                        .setAction("jít cela2")
                        .setMessage("\n\nAktuální lokace: cela2\n" +
                                "Popis lokace: Poměrně velká cela s mnoha tmavými zákoutími. Raději buďte opatrný/á\n" +
                                "Někdo tě bruálně napadl zezadu.\n" +
                                "Ztratil/a jsi 20.0 zdraví."))
                .addStep(new Step()
                        .setAction("jít žalář"))
                .addStep(new Step()
                        .setAction("jít cela3")
                        .setMessage("\nTahle cela je zamčená."))
                .addStep(new Step()
                        .setAction("jít žalář"))
                .addStep(new Step()
                        .setAction("zahodit pochodeň")
                        .setMessage("\nNe, to tě opravdu nenechám udělat."))
                .addStep(new Step()
                        .setAction("jít cela2")
                        .setMessage("\nNěkdo tě napadl potom, co jsi vstoupil/a do cely a zabil tě."));
        JUST_AS_PLANED
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat postele"))
                .addStep(new Step()
                        .setAction("vzít polštář"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("útok zajíc"))
                .addStep(new Step()
                        .setAction("útok bílý_zajíc"))
                .addStep(new Step()
                        .setAction("útok šedý_zajíc"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("vzít kámen"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát generál taška"))
                .addStep(new Step()
                        .setAction("jít ghetto"))
                .addStep(new Step()
                        .setAction("prohledat mrtvé_tělo"))
                .addStep(new Step()
                        .setAction("vzít klíč"))
                .addStep(new Step()
                        .setAction("prohledat odpadky"))
                .addStep(new Step()
                        .setAction("vzít peníz"))
                .addStep(new Step()
                        .setAction("dát malá_holčička polštář")
                        .setMessage("\nAwwwwwwwwwwwwwwwwww. To je ale úplně úžasně chlupatý polštářek!!! Opravdu mi ho jen tak dáte?\n" +
                                "Malá_holčička ti dala na oplátku klacek."))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít průchod"))
                .addStep(new Step()
                        .setAction("mluvit stráž_průchodu"))
                .addStep(new Step()
                        .setAction("mluvit stráž_průchodu")
                        .setMessage("\nArmin: Něco ti dám, ale uvolni si předtím místo v batohu."))
                .addStep(new Step()
                        .setAction("zahodit kámen"))
                .addStep(new Step()
                        .setAction("mluvit stráž_průchodu")
                        .setMessage("\nArmin: Nemůžu vám moc pomoct, už tak neši rodinu bedlivě sledují, ale můžu vám dát tohle." +
                                "\nARMIN ti dal univerzální_klíč"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("prohledat truhla"))
                .addStep(new Step()
                        .setAction("zahodit peníz"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("dát stráž taška")
                        .setMessage("\nStráž: Woahhhh. Díky mlaďoši takováhle úcta k starším se cení. Pohlídali byste to tu chvilku místo mě?\n" +
                                " Jen si skočim na jedno a hned jsem zpátky"))
                .addStep(new Step()
                        .setAction("vzít pochodeň"))
                .addStep(new Step()
                        .setAction("jít žalář"))
                .addStep(new Step()
                        .setAction("jít cela3"))
                .addStep(new Step()
                        .setAction("zachránit_tua")
                        .setMessage("Hra skončila.")
                        .setEnding("\nTue byl zachráněn. Teď je čas vrátit se do tábora a už nikdy se na toto odporné místo nevrátit. \n" +
                                "Gratuluji k úspěšnému dokončení hry!"));
        GENERALS_ROCK
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("vzít kámen"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát generál kámen")
                        .setMessage("\nGenerál: ...Zbavte se jich.")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
        GENERAL_CHIT_CHAT
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("vzít kámen"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("mluvit generál"))
                .addStep(new Step()
                        .setAction("mluvit generál"))
                .addStep(new Step()
                        .setAction("mluvit generál")
                        .setMessage("General: Zabijte je, už jsem s nimi ztratil víc než dost času.")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
        GUARD_CHIT_CHAT
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát generál taška"))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("mluvit stráž"))
                .addStep(new Step()
                        .setAction("mluvit stráž")
                        .setMessage("Stráž: Řekl jsem vám, abyste odešeli, tady je malé varování.\n" +
                                " Dědek na tebe zaútočil a způsobil ti 5.0 poškození. Zbývá ti 22.0 zdraví."))
                .addStep(new Step()
                        .setAction("mluvit stráž")
                        .setMessage("Stráž: Měli jste mě poslouchat, už mám dost...")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
        TUES_STICK
                .addStep(new Step()
                        .setAction("pohlaví muž"))
                .addStep(new Step()
                        .setAction("jméno j"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("zbraň sekera"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít jezero"))
                .addStep(new Step()
                        .setAction("prozkoumat velký_kámen"))
                .addStep(new Step()
                        .setAction("vzít svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("dát gorm svítící_kámen"))
                .addStep(new Step()
                        .setAction("jít místnost"))
                .addStep(new Step()
                        .setAction("odložitz"))
                .addStep(new Step()
                        .setAction("zbraň greatsword"))
                .addStep(new Step()
                        .setAction("jít kovárna"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít stan"))
                .addStep(new Step()
                        .setAction("prohledat postele"))
                .addStep(new Step()
                        .setAction("vzít polštář"))
                .addStep(new Step()
                        .setAction("prohledat papíry"))
                .addStep(new Step()
                        .setAction("vzít propustka"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít hora"))
                .addStep(new Step()
                        .setAction("útok zajíc"))
                .addStep(new Step()
                        .setAction("útok bílý_zajíc"))
                .addStep(new Step()
                        .setAction("útok šedý_zajíc"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("prohledat velký_strom"))
                .addStep(new Step()
                        .setAction("vzít taška"))
                .addStep(new Step()
                        .setAction("jít kemp"))
                .addStep(new Step()
                        .setAction("jít alej"))
                .addStep(new Step()
                        .setAction("útokp přerostlý_troll"))
                .addStep(new Step()
                        .setAction("útok přerostlý_troll"))
                .addStep(new Step()
                        .setAction("jít brána"))
                .addStep(new Step()
                        .setAction("dát stráž_brány propustka"))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("dát generál taška"))
                .addStep(new Step()
                        .setAction("jít ghetto"))
                .addStep(new Step()
                        .setAction("prohledat mrtvé_tělo"))
                .addStep(new Step()
                        .setAction("vzít klíč"))
                .addStep(new Step()
                        .setAction("dát malá_holčička polštář")
                        .setMessage("\nAwwwwwwwwwwwwwwwwww. To je ale úplně úžasně chlupatý polštářek!!! Opravdu mi ho jen tak dáte?\n" +
                                "Malá_holčička ti dala na oplátku klacek."))
                .addStep(new Step()
                        .setAction("jít město"))
                .addStep(new Step()
                        .setAction("jít vchod"))
                .addStep(new Step()
                        .setAction("útok stráž"))
                .addStep(new Step()
                        .setAction("vzít pochodeň"))
                .addStep(new Step()
                        .setAction("jít žalář"))
                .addStep(new Step()
                        .setAction("jít cela3"))
                .addStep(new Step()
                        .setAction("dát tue klacek")
                        .setMessage("Tue: Kla--kla-cek opravdu mi prostě dáš klacek??? Jsem vám opravud až tak pro smích???\n" +
                                "///Tuovi, kterému po několika dnech strávených na tomoto příšerném místě, zbývala už jen trocha síla na to, aby se udržel při smyslech, \n" +
                                "tvoje nabídka klacku způsobila šok, který ho připravil o zbytek rozumu.  Popadl klacek a vší silou, tě s ním začal bodat a zabil tě.")
                        .setEnding("\nHra skončila. Prohrál/a jste."));
    }}

